version: '3.7'

services:
  sankhya-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Porta da aplicação
      - "5005:5005" # Porta de depuração
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sankhya_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 # Configuração de depuração
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sankhya_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true
